# Generated by Django 3.1.6 on 2021-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addNotice',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
