# Generated by Django 3.2.5 on 2021-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_title_addnotice_title_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnotice',
            name='year',
            field=models.CharField(default='ALL', max_length=4),
        ),
    ]
