# Generated by Django 3.2.5 on 2021-09-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_admin',
            new_name='is_Admin',
        ),
    ]
