# Generated by Django 3.2.5 on 2021-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_is_admin_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
