# Generated by Django 3.2.5 on 2021-09-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_Admin',
        ),
    ]
