# Generated by Django 3.2.5 on 2021-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Admin_Status',
            field=models.BooleanField(default=False),
        ),
    ]
