# Generated by Django 3.2.5 on 2021-09-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210918_1215'),
        ('user', '0006_profile_admin_status'),
    ]

    operations = [
    ]
