# Generated by Django 3.2.5 on 2021-09-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_addnotice_year'),
        ('user', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.addnotice'),
        ),
    ]
