# Generated by Django 3.2.7 on 2021-09-24 11:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='settings.MEDIA_ROOT/photo/anonymous.jpg', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='photo'),
        ),
    ]
