# Generated by Django 3.1.6 on 2021-09-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_photo'),
        ('user', '0009_auto_20210923_0953'),
    ]

    operations = [
    ]
