# Generated by Django 3.2.5 on 2021-09-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_photo'),
        ('user', '0010_acknowledgment'),
    ]

    operations = [
    ]
