# Generated by Django 3.1.6 on 2021-09-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20210925_0940'),
        ('user', '0011_merge_0009_profile_photo_0010_acknowledgment'),
    ]

    operations = [
    ]
