# Generated by Django 3.2.5 on 2021-09-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20210926_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Notice',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
